# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Run all checks via Makefile
        run: make ci-check
